ユーザー詳細画面
yuta-kanashiro/Twitter-clone pull request #3
Opened 2022-08-15 06:52 UTC by yuta-kanashiro

## 実装した機能

### フロントエンド（Vue3）

- ユーザー詳細画面
  - UserListShowコンポーネントの作成
  - FollowButtonコンポーネントの作成
  - フォロー一覧へのリンク（リンクだけ。まだ画面なし）
  - ツイート詳細画面へのリンク（リンクだけ。まだ画面なし）
  
### バックエンド（Laravel8）

- ユーザー情報取得API
  - UserControllerのshowアクション追加
 
- フォロー機能API
  - FollowControllerのfollow、unfollowアクション追加

## 変更内容

### ユーザー詳細画面（ログインユーザー）

<img width="1088" alt="スクリーンショット 2022-08-15 15 43 49" src="https://user-images.githubusercontent.com/77533516/184589329-683a8343-e18a-41b2-ac85-c1f945ddd09e.png">

### フォロー前

<img width="1091" alt="スクリーンショット 2022-08-15 15 40 13" src="https://user-images.githubusercontent.com/77533516/184589372-df599088-74df-4294-85b9-d798e558d7f6.png">

### フォロー後

<img width="1080" alt="スクリーンショット 2022-08-15 15 40 42" src="https://user-images.githubusercontent.com/77533516/184589403-8707efac-d96e-4a41-8d16-68568d6e447c.png">

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(Auth::id());
さっき話したけど一応！Auth::id()はauth()->id()でもかけるよ。

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +        if (!$existing && !$myself){
フォロー判定してていいね！

でもここもう少しスッキリ書けそうな気がする！
フロントで制御するのもありなので、他の人のコード見たりして直してみて！(余裕があれば)

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +    public function follow(int $id)
基本的にコメントはPHP Docに書くので、内側にはあんまり書かないかな！

コード書く時は、まずはメソッド名・変数名をわかりやすく書く！それでもわかりにくい部分はコメント書いとく！というイメージなのでもう少しコメント減らしてもいいね！

見やすいコードを意識しているのは伝わるので、メソッド名とかコードの命名でそれを表現できたら良いと思う！

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +    public function unfollow($id)
引数`$followUserId`にしといた方がわかりやすそう！

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +        if ($existing && !$myself){
同じ処理は関数にして共通化するとコードがスッキリするので、意識してもいいかも

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/UserController.php
> +    *
空白消しちゃってください！

2022-08-15 09:42 UTC, mizok-o commented on src/app/Http/Controllers/UserController.php
> +            'loginUserId' => $loginUserId,
$loginUserId1回しか使ってないので変数に入れなくても良いよ！

2022-08-15 09:42 UTC, mizok-o commented on src/app/Models/User.php
> +    # ユーザーに関する処理
このコメントの書き方若干違和感あるけどどうなんだろう！
社員さんに見てもらった方がいいかな

2022-08-15 09:42 UTC, mizok-o commented on src/app/Models/User.php
> +    public function followCheck($followUserId): bool
intが抜けてる！docも！

2022-08-15 09:42 UTC, mizok-o commented on src/app/Models/User.php
> +    public function countFollowings()
返り値抜けてる！

2022-08-15 09:42 UTC, mizok-o commented on src/database/seeders/UsersTableSeeder.php
> +        foreach($followingUsers as $followingUser){
ここもコメント減らす意識してみてほしい！

2022-08-15 09:42 UTC, mizok-o commented on src/resources/js/components/FollowButton.vue
> +        <div class="follow" v-if="!isFollowing" @click="follow">
今divタグ1つの中に、button2つ入れて、表示非表示切り替えるやり方でやってみてほしい！
ボタンにv-if付けるかクラス付与するかどっちでもやれる！(もっと良いやり方あるかも

2022-08-15 09:42 UTC, mizok-o commented on src/resources/js/components/FollowButton.vue
> +            await axios.get('/api/follow/' + id.value)
これって動いてる？？

2022-08-15 10:15 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(Auth::id());
このふたつの違いとか何かある？？パッと調べたけど出てこなかった！

2022-08-15 10:22 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        if (!$existing && !$myself){
フロントで制御するのは勉強したい！
ただ期間的に最後まで終わらせることを優先したいから、現状はこのままでいい？コメントアウトはスッキリさせようと思うけど、他にスッキリできそうなところある？

2022-08-15 10:29 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(Auth::id());
use 宣言いるかどうかかな？
早さとかはわからない！

2022-08-15 10:34 UTC, mizok-o commented on src/app/Http/Controllers/FollowController.php
> +        if (!$existing && !$myself){
followCheckのところでまとめて判定出来そう！

2022-08-15 10:45 UTC, yuta-kanashiro commented on src/app/Http/Controllers/UserController.php
> +    *
対応した！

2022-08-15 10:47 UTC, yuta-kanashiro commented on src/app/Http/Controllers/UserController.php
> +            'loginUserId' => $loginUserId,
すまん、詳しく教えてほしい！！！どういうことだ？？

2022-08-15 10:47 UTC, yuta-kanashiro commented on src/app/Models/User.php
> +    # ユーザーに関する処理
整理する気持ちで試しに入れてみた！じゃあ一旦放置しておくね！

2022-08-15 10:47 UTC, mizok-o requested changes

2022-08-15 10:47 UTC, mizok-o commented on src/resources/js/components/UserList.vue
>                                  <div v-if="user.profile_image === null">
=== null使わないやり方でもいけるよ！
js false判定色々あるので試してみて！

比較演算子
https://jsprimer.net/basic/operator/

2022-08-15 10:47 UTC, mizok-o commented on src/resources/js/components/UserListShow.vue
> +import dayjs from "dayjs";
なくても行けると思う！
ライブラリ使ってみるのは良いことなので直す必要は無いです！

2022-08-15 10:47 UTC, mizok-o commented on src/routes/api.php
> +    Route::get('/follow/{id}', [FollowController::class, 'follow']);
get はデータの取得のみに使う！

データの保存、更新、削除などは全てpostメソッドでやります！

https://qiita.com/kanataxa/items/522efb74421255f0e0a1

2022-08-15 10:47 UTC, yuta-kanashiro commented on src/app/Models/User.php
> +    public function followCheck($followUserId): bool
対応した！

2022-08-15 10:49 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +            await axios.get('/api/follow/' + id.value)
動いてる！！何か気になるところあった？

2022-08-15 10:54 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +        <div class="follow" v-if="!isFollowing" @click="follow">
ありがとう！対応した！

2022-08-15 11:03 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +            await axios.get('/api/follow/' + id.value)
ありがとう！対応した！

2022-08-15 11:04 UTC, yuta-kanashiro commented on src/resources/js/components/UserListShow.vue
> +import dayjs from "dayjs";
おうけい！

2022-08-15 11:04 UTC, yuta-kanashiro commented on src/routes/api.php
> +    Route::get('/follow/{id}', [FollowController::class, 'follow']);
ありがとう！対応した！

2022-08-15 11:05 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +            await axios.get('/api/follow/' + id.value)
そう言うことね！getだったからか！理解した！

2022-08-15 11:20 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(Auth::id());
ありがとう！対応した！

2022-08-15 11:36 UTC, yuta-kanashiro commented on src/resources/js/components/UserList.vue
>                                  <div v-if="user.profile_image === null">
ありがとう！```!user.profile_image```にしてみた！

2022-08-15 12:11 UTC, yuta-kanashiro commented on src/app/Models/User.php
> +    public function countFollowings()
　ありがとう！対応した！

2022-08-15 13:43 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        if (!$existing && !$myself){
対応した！確認お願い！

2022-08-15 16:19 UTC, SakagenRyosuke reviewed
vue側のレビューしました！

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/components/FollowButton.vue
> +        }
結論：親コンポーネントで判定して、その値を渡してあげるのがいいと思う。

理由：この階層でフォローチェックしてしまうと、フォローリストを表示するときに、このコンポーネント使うと思うんだけど、そのときにユーザー一件ずつリクエストを送ってしまうため、`Too Many Requests`になってしまうから。ファボボタンとかコメントボタンとかにも通ずるよ。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/App.vue
>  }
ここに書くんじゃなくて、
共通のcssファイルを作るといいよ。`reset.css`とかも！

ちなみに、`router-link`は、aタグだよ。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/app/Http/Controllers/FollowController.php
> +    }
vue側で返り値どうなっているか確認してみて！

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/router.js
>      { path: '/', name: 'home', component: UserList },
`UserList`が`home`であってる？タイムラインが`home`な気がする。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/router.js
> +    { path: '/user-profile/:id', name: 'userProfile', component: UserListShow, props: true },
`component`と`name`が違うのは変じゃないかな。
`userProfile`で統一するといいよ。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/components/UserListShow.vue
> +        }
日付のフォーマットしてるのめっちゃいいね。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/components/UserListShow.vue
> +        const id = ref(Number(props.id));
Number型に変えなくていいと思う。

2022-08-15 16:19 UTC, SakagenRyosuke commented on src/resources/js/components/UserList.vue
>                                  <div v-else>
ここの部分わざわざv-ifで要素２つ用意する必要はなくて、
`img`を`:src="user.profile_image ?? '../img/default.png'"`に書き換えで十分だと思う。

参考：[Null 合体演算子 (??)](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

余談だけど、ユーザー登録した時点でプロフィール画像の値がなかったら`default.png`のパスを入れてあげるたら解決する気がする。

2022-08-16 02:04 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +        }
コメントありがとう！
てことはこの記述をそのまま親コンポーネントに移して、propsでFollowButton（子コンポーネント）に渡すって形でいいかな？

2022-08-16 02:06 UTC, SakagenRyosuke commented on src/resources/js/components/FollowButton.vue
> +        }
いえす！

2022-08-16 02:11 UTC, yuta-kanashiro commented on src/resources/js/App.vue
>  }
なるほど、aでも行けるのね！

2022-08-16 02:13 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +    }
１か空！だね！

2022-08-16 02:14 UTC, yuta-kanashiro commented on src/resources/js/router.js
>      { path: '/', name: 'home', component: UserList },
この場合ってhomeから変えたら、pathも```/```から変える？

2022-08-16 02:17 UTC, yuta-kanashiro commented on src/resources/js/router.js
> +    { path: '/user-profile/:id', name: 'userProfile', component: UserListShow, props: true },
ありがとう！対応した！

2022-08-16 02:20 UTC, yuta-kanashiro commented on src/resources/js/components/UserListShow.vue
> +        const id = ref(Number(props.id));
対応した！

2022-08-16 02:21 UTC, SakagenRyosuke commented on src/app/Http/Controllers/FollowController.php
> +    }
`v-if="!isFollowing"`でうまく制御できてるからいいんだけど、
bool型で帰ってきてないことを知って欲しかったからコメントした！！
結構衝撃じゃない？笑

2022-08-16 02:23 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +    }
そう！！！！！！激しく共感。笑
Laravel側でbool型で返そうとすると全く返ってこない。笑

2022-08-16 02:24 UTC, SakagenRyosuke commented on src/resources/js/router.js
>      { path: '/', name: 'home', component: UserList },
yes！普通に`/UserList`でいいと思うよ。

余談：俺は、`/`だと今いる場所が分かりにくいから、`/`でリダイレクト先を`/home`にしてたよー。

2022-08-16 04:00 UTC, yuta-kanashiro commented on src/resources/js/router.js
>      { path: '/', name: 'home', component: UserList },
タイムライン作った後に変更した方がよいよね？？

2022-08-16 04:08 UTC, SakagenRyosuke commented on src/resources/js/router.js
>      { path: '/', name: 'home', component: UserList },
いいと思う！

2022-08-16 05:17 UTC, yuta-kanashiro commented on src/resources/js/components/FollowButton.vue
> +        }
すまん、全然うまくいかない

2022-08-17 03:32 UTC, SakagenRyosuke approved these changes

2022-08-18 01:31 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +    * フォロー済みかチェック（フォローしていればtrue,フォローしていなければfalseを返す）
実際の返り値は `int` になっているので、以下どちらかの対応をした方がいいと思います！
- コメントアウトを修正する
- returnする値を変える

2022-08-18 01:34 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +    public function followCheck(int $followUserId): int
booleanを返すメソッドの命名について、参考になりそうな記事を載せておくのでお手隙のタイミングで見てみてください！
[booleanメソッドの命名規則](https://qiita.com/GinGinDako/items/6e8b696c4734b8e92d2b)

今回の例で言うと、`followCheck()` よりも `isFollowed()` の方がどういう返り値なのか直感的に分かりやすいと思います！

2022-08-18 01:37 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(auth()->id());
`$loginUser = User::find(auth()->id())`
を
`$loginUser = auth()->user();` にしても挙動変わらないと思うので試してみてくださいー！

参考 : https://qiita.com/ucan-lab/items/a7441bff64ff1f173c10

2022-08-18 01:49 UTC, s-wada523 commented
@yuta-kanashiro 
何点かコメントしたので確認お願いしますー！

2022-08-18 03:33 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +    * フォロー済みかチェック（フォローしていればtrue,フォローしていなければfalseを返す）
コメントありがとうございます！対応します！

2022-08-18 03:37 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +    public function followCheck(int $followUserId): int
ありがとうございます！ご意見をいただきたくて、

```followCheck```→```isFollowing```
```existsing```→```isFollowingExists```
```myself```→``isUserMyself```

こちらはいかがでしょうか？

2022-08-18 03:38 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(auth()->id());
挙動としては変わらないんですけど、```auth()->user()```だったり```Auth::user()```すると、
画像のようにvsCode上でエラーが出ます！

<img width="681" alt="スクリーンショット 2022-08-18 12 31 37" src="https://user-images.githubusercontent.com/77533516/185287188-a6abe362-d1bf-41d0-adbf-43a3ca1925ba.png">

2022-08-18 04:07 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +    public function followCheck(int $followUserId): int
`isFollowingExists` よりは `followingExists` がいいかな！
参考 : https://qiita.com/yskszk/items/5a7f99c974773f03a82a

`isUserMyself` は `isMyself` でもいいかも！

大事なのは、変数名やメソッド名を一目見ただけで、「どんな役割を持っているのか」が明確にわかることだと思います！
その上で、英語の文法とか考えればいいかなと思います！

ネーミングを決めるときに便利なツールがあるので参考までに！
[codic](https://codic.jp/engine)

![image](https://user-images.githubusercontent.com/79426711/185291364-12828e5f-b428-44ce-b83b-840cf4492729.png)

2022-08-18 04:10 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(auth()->id());
僕の確認ミスでした🙏

`follow()` はUserクラスに持たせてるメソッドなんだね！
だったら、`Auth::user()` を使ってしまうとメソッドを呼び出せなくなってしまうから、元の形に戻してもらえると！

2022-08-18 04:18 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +    public function followCheck(int $followUserId): int
ありがとうございます！勉強になります！
この場合だと、UserProfileのapiを呼び出している関数の命名も```followCheck```なのですが、そちらも変更した方が良さそうですか？

2022-08-18 04:19 UTC, yuta-kanashiro commented on src/app/Http/Controllers/FollowController.php
> +        $loginUser = User::find(auth()->id());
承知しました！！！

2022-08-18 04:23 UTC, s-wada523 commented on src/app/Http/Controllers/FollowController.php
> +    public function followCheck(int $followUserId): int
そうだね！

2022-08-18 05:25 UTC, s-wada523 approved these changes
## LGTM!

![LGTM](https://image.lgtmoon.dev/177749)

2022-08-18 06:10 UTC, merged